---
- hosts: all
  become: true

  vars:
    build_root: /vagrant/
    bash_aliases:
      - { alias: 'mariadb', command: 'mysql -u root -pogn -h 172.17.0.2' }
      - { alias: 'sql', command: 'mysql -u root -pogn -h mariadb' }

  pre_tasks:
    - name: Update apt cache if needed.
      apt: update_cache=yes cache_valid_time=3600
    - name: Upgrade.
      apt: upgrade=yes
    - name: Install Ansible
      apt: name=ansible state=present
    - name: Update ansible collection community.mysql.
      command: ansible-galaxy collection install community.mysql
    - name: Install Maria-DB Client
      apt: name=mariadb-client state=present
    - name: Install PHPMYADMIN
      apt: name=phpmyadmin state=present
    - name: Autoremove
      apt: autoremove=yes

  tasks:
    - name: Bash aliases | Add aliases
      become: no
      lineinfile:
        dest: "~/.bash_aliases"
        create: yes
        mode: 0644
        line: 'alias {{ item.alias }}="{{ item.command }}"'
        regexp: "^alias {{ item.alias }}="
      with_items: "{{ bash_aliases }}"
      when: bash_aliases != false

    - name: Copy 
      become: no
      copy:
         src: "../aliases"
         dest: /tmp/aliases

    - name: Gen aliases
      become: no
      shell: /tmp/aliases

    - import_tasks: setup.yml
    - import_tasks: docker.yml
    - import_tasks: basicpak.yml
